### ISSUE TITLE
make_sure_its_a  converts np.ma.MaskedArray into np.Array

### ISSUE THREAD

**Issue by lbusoni** [ArcetriAdaptiveOptics/arte#46]
The test below fails, and converts the MaskedArray v into a np.Array with nan's in the masked values.  This is preventing to use masked array with TimeSeries
  
```
def test_make_sure_its_a_with_masked_array_returns_masked_array(self):
        mask = np.array([[True, False], [False, False]])
        data = np.arange(4).reshape((2, 2))
        v = np.ma.array(data, mask=mask)
        c = make_sure_its_a(u.m, v)
        self.assertTrue(isinstance(c, np.ma.MaskedArray))
        self.assertFalse(np.isnan(c).any())
```

**Comment by alfiopuglisi** [comment]
Turns out that Astropy does not support masked arrays, and instead has its own type astropy.utils.masked.Masked, which behave similar to numpy masked arrays but with some differences:

https://docs.astropy.org/en/stable/utils/masked/index.html

we have to decide whether to support it or not, I created a branch "astropy_masked" where I updated the unit_checker routines to support it and added the test (and some others) to experiment a bit.

**Comment by lbusoni** [comment]
Not clear to me why Masked is needed  when we can have a traditional MaskedArray whose data is quantified...

```
In [17]:         mask = np.array([[True, False], [False, False]])
    ...:         data = np.arange(4).reshape((2, 2))
    ...:         v = Masked(data, mask=mask) * u.s

In [18]: v
Out[18]: 
<MaskedQuantity [[——, 1.],
                 [2., 3.]] s>

In [19]:         mask = np.array([[True, False], [False, False]])
    ...:         data = np.arange(4).reshape((2, 2))*u.s
    ...:         v2 = np.ma.MaskedArray(data, mask=mask)

In [20]: v2
Out[20]: 
masked_Quantity(
  data=[[--, 1.0],
        [2.0, 3.0]],
  mask=[[ True, False],
        [False, False]],
  fill_value=1e+20)

In [22]: v[1,1]
Out[22]: <MaskedQuantity 3. s>

In [23]: v2[1,1]
Out[23]: <Quantity 3. s>
```

**Comment by alfiopuglisi** [comment]
Probably because such a MaskedArray is not a subclass of Quantity, and therefore it is difficult to detect that it has a quantity inside without lots of manual checking, which in their library must happen a lot.
In our case I just made a special case for make_sure_its_a() in this branch:

https://github.com/ArcetriAdaptiveOptics/arte/tree/46-make_sure_its_a-converts-npmamaskedarray-into-nparray
